# Generated by Django 5.0 on 2023-12-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albom',
            name='rasm',
            field=models.FileField(blank=True, null=True, upload_to='rasmlar'),
        ),
        migrations.AlterField(
            model_name='qoshiq',
            name='fayl',
            field=models.FileField(null=True, upload_to='musiqalar'),
        ),
    ]
